### ISSUE TITLE
Unable to upload my file

### ISSUE THREAD

**Issue by Florian-Des** [Gregory-Gerard/xdrop#5]
I am experiencing an issue with uploading my file larger (1.39 Go) on xdrop.com. 
According to the README, the limit for uploads is 10GB, but I am consistently unable to upload files that exceed 1GB in size.

to reproduce...
1. Go to xdrop
3. Attempt to upload a file larger than 1GB 
5. After some time, notice that the upload either fails or stops unexpectedly with message "**Fichier trop gros (10 GB max.)"**

I expected to be able to upload files up to 10GB as mentioned in the README... La recette est KO.

**Comment by Gregory-Gerard** [comment]
Good catch! You’re absolutely right; this was due to an Apache configuration limiting uploads to 1GB. I've updated the `LimitRequestBody` directive to allow larger file uploads, as detailed in the [Apache documentation](https://httpd.apache.org/docs/2.4/mod/core.html#limitrequestbody).

Thanks for pointing this out!
